### ISSUE TITLE
ERROR: There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by eyooooo** [PatrickAlphaC/chainlink_defi#2]
running `yarn` after cloning the repo throws the error in the subject.

**Comment by PatrickAlphaC** [comment]
Per [yarn github](https://github.com/yarnpkg/yarn/issues/2821):


You've got the wrong yarn 😄 The Yarn you're executing comes from the cmdtest package: http://manpages.ubuntu.com/manpages/xenial/man1/yarn.1.html. Uninstalling cmdtest should fix this. Once you've uninstalled it, follow the instructions on https://yarnpkg.com/en/docs/install#linux-tab to add the Yarn repo:

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn
```

**Comment by eyooooo** [comment]
yep! as you closed this i figured out yarn was wrong ;) thank you so much!!
