### ISSUE TITLE
Error when approving metamask tx quickly while trying to stake

### ISSUE THREAD

**Issue by samlaf** [PatrickAlphaC/chainlink_defi#6]
Hi Patrick,

thanks for this awesome repo and accompanying tutorial.
I noticed a bug while trying to use your app, which I'm not 100% sure how to fix so decided to submit this issue.

When I click on STAKE!, the app first asks to approve the LINK token, and then sends the staking transaction.
If I approve the first metamask tx very very fast after the "confirm" buttons becomes available:
![image](https://user-images.githubusercontent.com/9342524/149808854-6d97dcb6-9893-4d88-bd44-2b67099b00da.png)

I get this error
![image](https://user-images.githubusercontent.com/9342524/149808754-ecf1b7f8-b23b-4fc3-b24c-e0be9b6e61a1.png)

## Potential Solution

Even if the stack traces are useless (or at least I don't understand them), I figured the error happens in the stakeTokens function:
```
  stakeTokens = (amount, tokenAddress) => {
    this.setState({ loading: true })
    this.state.erc20.methods
      .approve(this.state.tokenFarm._address, amount)
      .send({ from: this.state.account })
      .on("transactionHash", (hash) => {
        this.state.tokenFarm.methods
          .stakeTokens(amount, tokenAddress)
          .send({ from: this.state.account })
          .on("transactionHash", (hash) => {
            this.setState({ loading: false })
          })
      })
  };
  ```

One potential solution is to change `.on("transactionHash")` to `.on("receipt)` but that makes for a much worse UI since we have to wait for the first tx to be written to a block. Is there any other way that this could be solved?

**Comment by PatrickAlphaC** [comment]
Hmm... I'm not sure I'm getting this error. But you're right. Something odd is going on....

**Comment by samlaf** [comment]
After a few tests I don't think it's actually got to do with the speed at which I click haha...
It seems to be.. first time doesn't work, refresh and redo, and then it goes through (oh just realizing that's similar to waiting for the first tx to be included in a block).
Is there something that could be preventing the two txs from being included in a single block?
I'll try to figure it out later, but if you have any idea that could be helpful.

**Comment by samlaf** [comment]
Playing again with this this morning.
Found this thread which talks about the same issue: https://github.com/MetaMask/metamask-extension/issues/13197
Most people are recommending switching to an async/await syntax, which I believe is equivalent to `.on("transactionHash")` to `.on("receipt")`, so kind of out of question.

One thing I realized though is that metamask will warn the user about the 2nd tx possibly failing
![image](https://user-images.githubusercontent.com/9342524/149986020-6cf5f2f1-68cd-4708-9878-4de20a9c852d.png)
since it can't for sure know that the first approve will have passed (this is why the async/await helps!). But if you click on I will try anyway, the 2nd tx gets included in a later block and everything is fine.

**Comment by samlaf** [comment]
I've also found the *actual* reason for that first bug I sent! Not sure if it's a problem with the way the frontend is coded or if its a metamask problem.
If you click on "STAKE!" again while the first staking tx is still queued:
![image](https://user-images.githubusercontent.com/9342524/149987254-2b7b7167-e644-4372-aeb7-83d7444eea9e.png)
Then you get the bug...

**Comment by samlaf** [comment]
Sorry for the spam... but I've definitely figured this one out this time. And it's definitely a metamask problem.
I explained the problem in extensive details here in case anyone is interested: https://github.com/MetaMask/metamask-extension/issues/13197#issuecomment-1015697640

**Comment by PatrickAlphaC** [comment]
Not spam! This is great feedback! 

Wow! This is great that you found this!! 

It looks like we could write some code to stop people from continuing till after their transaction goes through... What do you think ?

**Comment by samlaf** [comment]
You mean just in this repo, or in metamask?

**Comment by samlaf** [comment]
And by "we" you mean me right? ;)
I would probably just go for the lazy solution and wait on the first tx...

**Comment by PatrickAlphaC** [comment]
This repo.

We means anyone! This is an open sourced project. It could be me.... It could be you, but it's ok if we don't make this fix. I might have to just update the readme... 

Yeah I think the lazy solution might be the right approach.

**Comment by samlaf** [comment]
:)
Actually one other possible solution is to hardcode the gas limit in the transaction directly.
One possible downside is that if the smart contract ever upgrades, or ethereum decides to change gas prices, it might change.
We could also just put a 200K gas limit or whatever... and hope that the tx doesn't hit a failing assert.
What do you think?

**Comment by PatrickAlphaC** [comment]
hmmm.... yeah. This is why most professional solidity devs don't use `transfer`, since it has hard gas requirements that may change in the future. 

grrrr.... Might make sense just to go with lazy for now... This is just a demo project anyway...

**Comment by samlaf** [comment]
Yeah... I sent the PR: https://github.com/PatrickAlphaC/chainlink_defi/pull/7#issue-1110631322
We might want to change a bit the frontend since now it just says "loading" and there's no indication that it's ever going to stop loading... I'll leave that to others.

**Comment by PatrickAlphaC** [comment]
Thank you for this! 
I think we can close now?

**Comment by samlaf** [comment]
yep
